@startuml

/'title
  Simple ISA simulator
end title '/

partition "main" {
  start
}

:prog*
progSize
regFile*; <<input>>

partition "ISA simulator" {
  :Allocate stack memory
  Initialise stack;
  :PC = 0;
while (PC < progSize?) is (Yes)
    :Load instruction;
    :Increment PC;
    :Decode Instruction;
    :Execute instruction;
    note left
      Main component:
      Switches over decoded instructions
      and perform operations that changes
      program state e.g:
      ALU operations, branch, load, store.
      ====
      Can exit early via //ecall// instruction.
    end note
endwhile (No)
  :Free stack memory;
}

:prog*
regFile*
returnStatus; <<output>>

partition "main" {
  stop
}

@enduml
